### PR TITLE
Add cpct_memset_fxx_i functions interrupt Friendly

### PR DESCRIPTION
**Pull request by Arnaud6128**
Add _cpct_memset_f64_i_ and _cpct_memset_f8_i_.

### CODE REVIEW

**Comment by lronaldo** [comment]
Hi @Arnaud6128 

   I'm currently reviewing these two functions. `cpct_memset_f64_i` can be useful in some cases, if you can syncronize it with your interrupts or you don't need your interrupts to be very precise whenever you use it. It can be useful.

   However, `cpct_memset_f8_i` makes almost no sense. Adding the overhead of setting and resetting SP eats up 23 of the 24 microsecons of benefit you get from using the stack. Gaining only 1 microsecond per block of 8-bytes you copy makes it worse in general than using then normal `cpct_memset`, which is also interrupt friendly. You need to copy 30 or more blocks of 8-bytes (> 240 bytes) to start getting some benefit in terms of microseconds. In that case, most of the time you will prefer using `cpct_memset_f64_i`. There are really few use-cases for this new version of the function. I think is preferably, in general, using `cpct_memset` instead.

   So, my proposal would be to maintain `cpct_memset_f64_i` but dropping `cpct_memset_f8_i`.

   What do you you think about it?

**Comment by Arnaud6128** [comment]
Ok i understand, _cpct_memset_f8i_ is finally not really useful.

**Comment by lronaldo** [comment]
I have reviewed and improved `cpct_memset_f64_i`. Could you please test it several times to check that it works as expected? I have added some optimizations but didn't have time to test it. 

If it works as expected, I will proceed to merge it with current development branch.

**Comment by Arnaud6128** [comment]
Tested by modifing the fastmemset example. All is OK.

**Comment by lronaldo** [comment]
Nice, @Arnaud6128. Thank you very much :)

**Pull request merged**
