### PR TITLE
Optimization of cpct_drawSolidBox based on cpct_drawSprite code

### PR DESCRIPTION
**Pull request by Arnaud6128**
Optimization of cpct_drawSolidBox based on cpct_drawSprite code

### CODE REVIEW

**Comment by lronaldo** [comment]
Really great work, @Arnaud6128. Indeed, this function should have been reviewed long ago, as it was very early CPCtelera code and had much room for improvement. Your approach is really nice and clean, and has a great gain with respect to the original. Well done.

I've been reviewing your code and done two things: first I have reworked it to be API backwards compatible for ASM developers. This function is being used by a lot of code and breaking it would be painful for many developers. Second, I have figured out a way to improve your approach and gain another  ~10%. I will accept your pull request and add my changes to have backwards compatible version with all gains from your approach and my review.

**Comment by lronaldo** [comment]
I made a mistake with commits, but I've merged your changes and mine's. Everything is now added to current development branch.

I have only tested it for ASM projects. Could you please test it for C projects and confirm that it works as expected?

Thanks :)

**Comment by Arnaud6128** [comment]
Correction for C binding in pull request

**Comment by lronaldo** [comment]
Right you are. Thank you for your quick review.

Everything is now merged and working fine :)

**Pull request closed without merging**
