### PR TITLE
Arnaud6128 back buffer

### PR DESCRIPTION
**Pull request by Arnaud6128**
Add cpct_drawToSpriteBufferMasked function

### CODE REVIEW

**Comment by lronaldo** [comment]
Hi @Arnaud6128 

   I see you are doing a big amount of great work. Nice, man :). I really appreciate it.

   With respect to these functions, I would advice to thorougly review them, one by one. Including several functions on the same push is too much work and disperses concentration and focus on important things. I think is preferably to go step by step. This is a slow process, but I think is preferably to do things slowly, but with great quality.

    With respect to the function proposal cpct_drawToSpriteBufferMasked, I have these questions:
- Have you tested it? After reading it, it seems it shouldn't work as expected. It uses the width of the sprite in the same way as cpct_drawToSpriteBuffer, which should be incorrect. It should increment twice this quantity, as the sprite includes a mask, which doubles its size. This should be taken into account in order to review code and functionality.
- Documentation may need to be reviewed at least twice. I often review documentations two or three times to improve them. Documentation is key for enabling people to use and understand functions. For instance, when explaining the *width* parameter, it is important to tell de user that *width* does not account for the mask (or it does, depending on the API design). If not, the user cannot tell. A 4-bytes-wide sprite uses another 4-bytes for mask. Should the *width* be 4 or 8 bytes? These details are extremelly relevant for users. Doing a proper documentation is, from my point of view, much harder than doing a properly optimized code.
- Another thing to take into account is interrelations. If your API needs a *width* including the mask (8 bytes in our previous example) then *buffer_width* might be lower than *width* but correct. If you draw a 8-bytes-wide sprite including mask into a 6-bytes-wide sprite buffer, that is okay. And that might result extremely confusing for the user. 2 width parameters that have to be considered differently in the same call.
- There is no need to repeat the mask information from cpct_drawSpriteMasked. In fact, there is no need to repeat most of that information. You can tell the user to review cpct_drawSpriteMasked for details, including a link. It is important to focus de description on the important things of this function, like it draws to a Sprite buffer. So, it does not do it similar to <cpct_drawSprite> as the description says, but similar to <cpct_drawSpriteMasked>.

I expect to have some time soon to help you with revision, as I did with previous function. In the mean time, you may perform some of these checks. We will surely have a great and polished final version to publish, mostly thanks to your great work :).

**Comment by Arnaud6128** [comment]
Hi @lronaldo,
- i have compiled and tested with my example, and it seems to work in local.
- OK, i'll take into account your remarks on documentation

**Comment by lronaldo** [comment]
@Arnaud6128 

   I have also noticed that you are not saving IX when using it. That may work out of luck, but it will create lateral effect problems with different uses for sure. As I removed it from cpct_drawToSpriteBuffer, it has passed as something hidden. Functions will require revision or some careful redesign. Please, take into account.

   With respect to the width of the sprite, you are right, it works. I was mistaken because the width of the sprite including the mask is not actually used when drawing to a sprite buffer that does not have mask on it. Inside the sprite buffer, only the actual width of the sprite (without its mask) is what counts. That's why it works. So, regarding this point, it is okay :).

**Comment by Arnaud6128** [comment]
Ok i'll add :
```
push ix; Save ix before making changes
...
pop ix; Restore IX before returning
```
To the three functions.

**Comment by lronaldo** [comment]
@Arnaud6128 I have worked out an optimization for <cpct_drawToSpriteBufferMasked> that also gets rid of IX. Also, I think we might apply this optimization to >cpct_drawToSpriteBuffer> in a similar way. I have not tested the code, could you please test and measure it?

Please, notice the API change: Instead of height, width, sprite, it now is width, height, sprite.
```
;;;------------------------------------------------------------------------------------------
;;;  sprites.h
;;;------------------------------------------------------------------------------------------
// Sprite to Sprite-Buffer Drawing Functions
extern void cpct_drawToSpriteBufferMasked (u16 buffer_width, void* buffer, u8 width, u8 height, void* sprite) __z88dk_callee;

;;;------------------------------------------------------------------------------------------
;;;  cpct_drawToSpriteBufferMasked_cbindings.s 
;;;------------------------------------------------------------------------------------------
.module cpct_sprites

.include "../macros/cpct_maths.s"    

;;
;; C bindings for <cpct_drawToSpriteBufferMasked>
;;
;;   19 us, 6 bytes
;;
_cpct_drawToSpriteBufferMasked::
   ;; GET Parameters from the stack following __z88dk_callee convention
   pop hl        ;; [3] HL= Return Address
   pop bc        ;; [3] C = Back_Buffer_Width (B is ignored)
   pop de        ;; [3] DE= Pointer to Back Buffer 
   ld  a, c      ;; [1] A = Back_Buffer_Width
   pop bc        ;; [3] B = Sprite Height, C = Sprite Width
   ex (sp), hl   ;; [6] HL = Pointer to Sprite,
                 ;;    (SP) = Return Address. This address is the only required
                 ;;    thing to be kept in the stack with this convention.


;;;------------------------------------------------------------------------------------------
;;;  cpct_drawToSpriteBufferMasked.asm
;;;------------------------------------------------------------------------------------------
   ;; Calculate offset to be added to Destiny pointer (DE, BackBuffer Pointer)
   ;; After copying each sprite line, to point to the start of the next line
   sub c                         ;; [1] A = Offset = Back_Buffer_Width - Sprite Width
   ld (offset_to_next_line), a   ;; [4] Modify the offset size inside the copy loop

   ;; Modify the Sprite Width in the placeholder that is located inside the copy loop.
   ;; This lets the copy loop to easily restore the Sprite Width on every iteration
   ld  a, c                      ;; [1] A = Sprite Width
   ld (sprite_width_restore), a  ;; [4] Modify the Sprite Width value inside the copy loop

   ;; Perform the copy
   copy_loop:
      sprite_width_restore = .+1
      ld c, #00         ;; [2] Restore Sprite Width into c to use it as counter for line_loop
                        ;;     (00 is a placedholder that will be self-modified)
      line_loop :
         ld    a ,(de)  ;; [2] Get next background byte into A
         and (hl)       ;; [2] Erase background part that is to be overwritten (Mask step 1)
         inc  hl        ;; [2] HL += 1 => Point HL to Sprite Colour information
         or  (hl)       ;; [2] Add up background and sprite information in one byte (Mask step 2)
         ld  (de), a    ;; [2] Save modified background + sprite data information into memory
         inc  de        ;; [2] Next bytes (sprite and memory)
         inc  hl        ;; [2] 
   
         dec   c        ;; [1]   One less iteration to complete Sprite Width
      jr nz, line_loop  ;; [2/3] Repeat line_loop if C!=0 (Iterations pending)
      
      ;; Update the Destiny Pointer. DE must point to the place where the
      ;; next sprite line will be copied. So we have to add 'Backbuffer Width - Sprite Width'
      ;; which is the offset to the start of the next line to be drawn inside the sprite buffer
      ;;    DE + A (DE=Destiny Pointer inside the sprite buffer, A=Offset to next Line)
      offset_to_next_line = .+1
      ld  a, #00     ;; [2] A = Offset_to_next_line (00 is a place holder that will be self-modified)
      add_de_a       ;; [5] DE += A (Macro)

   djnz copy_loop    ;; [3/4] B--, One less iteration to complete Sprite Height
                     ;;          Repeat copy_loop if B!=0 (Iterations pending)

   ret               ;; [3] Return to the caller
```

**Comment by lronaldo** [comment]
I just forgot. I have created a set of useful macros for adding HL, BC or DE + A. You have them here https://github.com/lronaldo/cpctelera/blob/drawbackbuffer/cpctelera/src/macros/cpct_maths.s

**Comment by Arnaud6128** [comment]
Ok, it works.

;;   Case      |   microSecs (us)   |     CPU Cycles
;;  -----------------------------------------------------
;;   Any       |  13 + (17 + 12W)H   | 52 + (68 + 48W)H
;;  -----------------------------------------------------
;;   W=2,H=16  |         749        |        2996
;;   W=4,H=32  |        2573        |        10292
;;  -----------------------------------------------------

**Comment by lronaldo** [comment]
Hi @Arnaud6128, 

As soon as I have some spare time, I will be including your pull request into the backbuffer branch of CPCtelera. Some parts of your code still need a bit of work, but we can continue polishing it up in its branch. You may create new pull requests to include your updates, while fetching changes I add myself to the main branch. Once everything is polished up, we will merge it with the development branch.

Some interesting things to do:
- Your backbuffer example does not include assets in their original format. Assets should be included in a subfolder (it may be assets/ img/ or similar, as you like). They should be automatically converted when the user types in make. For that, you need to include appropriate macro calls in the file image_conversion.mk.
- Also, I would suggest documenting and simplifying your example code. Reducing the length of your calls is important. Shorter lines are easier to understand and follow. Moreover, if appropriate comments are added to those lines, people wanting to learn will be better guided to understanding. For example, lines like this one:
```
cpct_drawSpriteMaskedAlignedTable((gPosScroll % 2) == 0 ? g_fire_0 : g_fire_1, GetBackScreenPtr(VIEW_X + POS_SHIP_X - G_FIRE_0_W, VIEW_Y + POS_SHIP_Y + 2), G_FIRE_0_W, G_FIRE_0_H, gMaskTable); 
```
are better understood if calculations are performed previous to the call and stored in variables. Moreover, there is no performance gain in including these in this form, as calculations need to be performed previously anyway. So, it is better to do something like this:
```
// Select sprite and calculate its byte-ptr location inside Sprite BackBuffer
u8* fireSp = (gPosScroll % 2) == 0 ? g_fire_0 : g_fire_1;
u8  x = VIEW_X + POS_SHIP_X - G_FIRE_0_W;
u8  y = VIEW_Y + POS_SHIP_Y + 2;
u8* backScrPtr = GetBackScreenPtr(x, y);

// Draw Sprite inside Sprite BackBuffer
cpct_drawSpriteMaskedAlignedTable(fireSp, backScrPtr, G_FIRE_0_W, G_FIRE_0_H, gMaskTable); 
```
And, of course, you should also comment each operation to tell the user what you are exactly doing. Most user will not understand calculations without an explanation of what and why are you doing them.

I think everything is getting really well polished. The final result will be brilliant :smile:

Nice work!

**Comment by Arnaud6128** [comment]
Hi @lronaldo, 
i have updated the example according your suggestions, tell me if you think something in code shall be more detailled.

**Comment by lronaldo** [comment]
Ok, @Arnaud6128 , It is much better now. We'll continue improving after merging.

Just one last bit. Remove generated code files like title.c/title.h, ship.c/ship.h... Those files don't need to be versioned at all. They are generated each time the user types in `make`, and having them versioned is even a problem. Just remove them, and we'll proceed to merging both branches.

Again, thank you for your work :smile:

**Comment by lronaldo** [comment]
Ok, @Arnaud6128 

   I have merged the branch and fixed two minor issues. Now everything is added to backbuffer branch and working. Please, fetch everything new to update your branch so that we can continue working on it. 

    As soon as I have some more free time I will perform another review of your code and update changes. Probably after this final review I will merge it to development branch and set it for inclusion in next release.

    You've done a great job, man 👍

**Pull request merged**
