### PR TITLE
Update global_functions.mk

### PR DESCRIPTION
**Pull request by Arnaud6128**
Add IMG2SPRITESMASK to generate Sprites Masked. 
Modification of command line with adding -im

### CODE REVIEW

**Comment by lronaldo** [comment]
Latest commit 244da584ce00c9348226ed8648588fe13eb1d66a introduces a new version of IMG2SPRITES that lets you generate sprites with or without interlaced mask at will. It also lets you select a different output folder for generated .C and .H output files. Both are controlled by parameters 7 and 8. For instance:
``
PALETTE={0 1 3 6 9 12 13 14 23 25 26}
$(eval $(call IMG2SPRITES,src/img/mysprites.png,0,g,8,8,$(PALETTE)))
``
This will convert mysprites.png into mode 0 sprites of size 8x8 pixels, using defined firmware $(PALETTE) values. All generated sprites will be named g_items_X[] (prefix g, suffix X, being X a number from 0 to the total number of sprites). With this method, no interlaced mask will be generated. If an interlaced mask is required, a seventh parameter containing the word "mask" should be used:
``
$(eval $(call IMG2SPRITES,src/img/mysprites.png,0,g,8,8,$(PALETTE),mask))
``
That will do the same as before, but generating interlaced mask for sprites, using 0 index as background colour. Generated files will be placed in src/img/ folder (where mysprites.png lies). To generate files in src/ folder, parameter 8 should have the desired output subfolder:
``
$(eval $(call IMG2SPRITES,src/img/mysprites.png,0,g,8,8,$(PALETTE),mask,src/))
``
This will make generated mysprites.c and mysprites.h files be moved to src/ folder after being generated. This functionality can also be used with nonmasked sprites in this way:
``
$(eval $(call IMG2SPRITES,src/img/mysprites.png,0,g,8,8,$(PALETTE),,src/))
``
Anything different from "mask" in parameter 7 will produce the same effect.

**Comment by lronaldo** [comment]
Also added support for generating tileset array (an additional array with pointers to all the sprites/tiles generated). In order to generate a tileset array, 7th parameter must contain the word "tileset", just like this:

```
PALETTE={0 1 4 8 9 10 12 13 14 17 18 20 21 23}
$(eval $(call IMG2SPRITES,src/img/mytiles.png,1,g,4,4,$(PALETTE),tileset,src/))
```

This command will convert `mytiles.png` into many 4x4 tile sprites for mode 1, using given `$(PALETTE)` and generating a `g_tileset` array containing pointers to all generated tiles. Resulting .C and .H files will be moved to `src/` folder.

**Comment by Arnaud6128** [comment]
I have error while generate image :

**Command:**
`$(eval $(call IMG2SPRITES,src/sprites/test.png,0,g,0,0,$(PALETTE), mask, src/sprites_src))`

**Log:**
Files 'src/sprites/test.c' and 'src/sprites/test.h' have been created with CPCtelera's codification of tiles/sprites from 'src/sprites/test.png'.

[testGenImg] Moving generated files:
[testGenImg]  - 'src/sprites/test.c' > 'src/sprites_src/test.c'
[testGenImg]  - 'src/sprites/test.h' > 'src/sprites_src/test.h'
mv: cannot move ‘src/sprites/test.c’ to ‘ src/sprites_src/test.c’: No such file or directory
mv: cannot move ‘src/sprites/test.h’ to ‘ src/sprites_src/test.h’: No such file or directory
cfg/build_config.mk:142: recipe for target 'src/sprites_src/test.c' failed
make: *** [src/sprites_src/test.c] Error 1

**Comment by lronaldo** [comment]
Your problem comes from including spaces in front of "mask" and output folder. Makefile macros take parameters literally, so folder " src/sprites_src" does not exist. 

I know this is not practical from user point of view, but that's how Makefile macros work.

**Comment by Arnaud6128** [comment]
All works, thanks.

**Pull request closed without merging**
